[application]
asset_dir = "assets"
name = "TrackFish"
android_manifest = "./AndroidManifest.xml"
main_activity = "./kotlin/MainActivity.kt"
android_min_sdk_version = 26

[web.app]
title = "TrackFish"

[bundle]
identifier = "com.example.Trackfish"
publisher = "Rhaskia"

icon = [
   "assets/icons/icon256.png",
   "assets/icons/favicon.svg",
]

category = "Music"

[bundle.windows]
icon_path = "assets/icons/icon256.png"
tsp = true
allow_downgrades = true

[bundle.windows.webview_install_mode.DownloadBootstrapper]
silent = false

